### ISSUE TITLE
How to Increase the quality(pixelRatio) like in react-image-crop?

### ISSUE THREAD

**Issue by raju10281** [codenaz/react-multiple-image-input#2]
How to increase the quality of Cropped Image?
while uploading the image of (5184 x 3880)
As result image uploaded to server is (330 x 441) which is very low, not readable text.

**Comment by raju10281** [comment]
How to increase the quality of Cropped Image?
while uploading the image of 5184*3880
As result image uploaded to server is 330*441 which is very low, not readable text.

**Comment by codenaz** [comment]
Closing this as it seems more like a request than an issue
