### ISSUE TITLE
Auto crop on multiple upload

### ISSUE THREAD

**Issue by Adiomojeed** [codenaz/react-multiple-image-input#4]
I am uploading multiple images, so, the modal for cropping only appears on the last picture. Is there a way to crop the image automatically once the image is clicked?

**Comment by codenaz** [comment]
@Adiomojeed You can crop the other Images by clicking on the edit button on them

**Comment by Adiomojeed** [comment]
Yes, I know that

But on the page I am using it, not all user will want to click the button after selecting the image and I want all images to gave same aspect ratio

So, it will be better if images can be automatically cropped once selected

**Comment by codenaz** [comment]
I see, so current workarounds are to set the minWidth and minHeight props so that your app rejects images that don't fit the specification, or you can set allowCrop to false so it just takes the user image as it is. The library doesn't support cutting or resizing images by default currently

**Comment by Adiomojeed** [comment]
Thanks for the clarifications
