### ISSUE TITLE
need to upload 4 images 320*320 how can we do that in react =hooks uploaded  attached image 

### ISSUE THREAD

**Issue by rohith231** [codenaz/react-multiple-image-input#5]
need to upload 4 images 320*320 how can we do that in react =hooks uploaded  attached image 
![im](https://user-images.githubusercontent.com/68227450/103564704-fed7d600-4ee4-11eb-8169-9754afd24a14.PNG)

**Comment by codenaz** [comment]
I don't think I totally get what you are asking, but you can pass a crop property to the cropConfig and specify the dimensions you want. You can also set a maxWidth and maxHeight prop. More details are in the ReadME file of the repo.
